# General settings
engineStrict: true
linkWorkspacePackages: true
minimumReleaseAge: 1440 # 1 day
packageManagerStrictVersion: true
strictDepBuilds: true
verifyDepsBeforeRun: error
#onlyBuiltDependencies: []
#ignoredBuiltDependencies: []

# No workspace
